class AR {
  static const Map<String, String> arabic = {
    "lastAdded":"المضاف حديثا",
    "offers":"العروض",
    "bestSeller":"الاكثر مبيعا",
    "category":"الاصناف",
    "wishlist":"المفضلة",
    "subcategory":"الاصناف الفرعية",
    "brand":"براند",
    "orders":"الطلبات",
    "setting":"الاعدادات",
    "Search":"ابحث",
    "langSetting":"اعدادات اللغة",
    "Notifications":"الاشعارات",
    "ShoopingCart":"سلة المشتريات",
    "NoItemsInYourCart":"لا يوجد عناصر في سلة المشتريات لديك",
    "ShppingNow":"تسوق الان",
    "login":"تسجيل الدخول",
    "EnterYourEmail":"ادخل البريد الاليكتروني ",
    "Email":"الايميل",
    "EnterYourPassword":"ادخل كلمة المرور",
    "Password":"كلمة المرور",
    "DontHaveACount":"ليس لديك حساب ؟",
    "SignUp":"اشتراك",
    "ForgetPassword":"هل نسيت كلمة المرور ؟",
    "noReviews":"لا يوجد اي تقيمات لهذا المنتج",
    "Reviews":"التقيمات",
    "phone":"رقم الهاتف",
    "enterPhone":"ادخل رقم الهاتف",
    "enterCountry":"ادخل الدولة",
    "country":"الدولة",
    "City":"المدينة",
    "enterCity":"ادخل المدينة",
    "zone-street":"المنطقة والشارع",
    "enterAddressDetails":"ادخل تفاصيل العنوان",
    "selectAddress":"اختر عنوان التوصيل",
    "confrimDeleteAddress":"تاكيد مسح هذا العنوان",
    "add":"اضافة",
    "cancel":"الغاء",
    "confirm":"تاكيد",
    "addNewAddress":"اضف عنوان جديد",
    "ChooseAddress":"اختر العنوان",
    "Orders":"الطلبات",
    "InProcess":"في التجهيز",
    "OnGoing":"في الطريق",
    "Delivered":"تم التوصيل",
    "Rejected":"تم الرفض",
    "noOrders":"لا يوجد طلبات لديك",
    "NoItemsInFavourite":"لا يوجد عناصر في المفضلة",
    "seeall":"مشاهدة الكل",
    "inprocess":"في التجهيز",
    "ongoing":"في الطريق",
    "delivered":"تم التوصيل",
    "rejected":"تم الرفض",
    "logout":"تسجيل الخروج",
    "lastWatched":"المشاهده مؤخرا",
    "profile":"الملف الشخصي",
    "addresses":"العناوين",
    "currency":"العملة",
    "language":"اللغة",
    "rateapp":"قيم التطبيق",
    "privacyPolices":"سياسة الخصوصية",
    "usagepolices":"سياسة الاستخدام",
    "aboutapp":"عن التطبيق",
    "vendorLogin":"تسجيل الدخول كبائع",
    "addtocart":"اضافة الي السلة",
    "buynow":"شراء الان",
    "store":"المخزن",
    "billdetails":"تفاصيل الفاتورة",
    "totalorders":"اجمالي الطلبات",
    "totalquantity":"اجمالي الكميات",
    "total":"الاجمالي",
    "continuetopurchase":"متابعة الشراء",
    "home":"الرئيسية",
    "account":"حسابي",
    "nosub":"لا يوجد فئات فرعية لهذا الصنف ",
    "noproduct":"لا يوجد منتجات في هذا العنصر",
    "chatsoon":"سيتم تفعيل الدردشة قريبا ",
    "SimillarProduct":"منتجات مشابهه",
    "government":"المحافظة",
    "followers":"التجار",
    "sellProducts":"عدد المبيعات من هذا المنتج",
    "NoAddresses":"لم تقم باضافة اي عنواين",
    ///////////////
    "confirm1":"متابعة الطلب",
    "name":"الاسم",
    "email":"البريد الالكتروني",
    "next":"التالي",
    "address":"العنوان",
    "shipping":"الشحن",
    "payment":"الدفع",
    "user":"المستخدم",
    "ShippingMethod":"طريقة الشحن",
    "Shippingbymerchant":"شحن عن طريق التاجر",
    "Shippingbyshippingcompany":"شحن بواسطة شركة شحن",
    "paymentmethod":"طريقة الدفع",
    "payment1":"الدفع عند الاستلام",
    "payment2":"بواسطة بطاقة الائتمان",
    "clientname":"اسم العميل",
    "BillDetail":"تفاصيل الفاتورة",
    "Totalorders":"مجموع الطلبات",
     "Confirmpurchase":"تاكيد الشراء",
    "products":"المنتجات",
    "ordersuccess":"تم الطلب بنجاح",
    "chooseaddress":"اختر عنوان الشحن",
    "selectColor":"اختر اللون",
    "selectSize":"اختر الحجم",
    "le":"جم",
    "confirmdelete":"تـأكيد الحذف من سلة المشتريات",
    "confrim":"تأكيد",
    "question":"اسئلة",
    "seeAll":"مشاهد المزيد",
    "reviews":"اراء العملاء",
    "selectall":"تحديد كل العناصر",
    "unselectall":"الغاء تحديد كل العناصر",
    "MoreDetails":"مزيد من التفاصيل",
    "colors":"الالوان",
    "specification":"الخصائص",
    "SellerRecommendations":"توصيات البائع",
    "addQuestion":"اضف سؤال",
    "forgetPassword":"نسيت كلمة المرور",
    "verification":"كود التفعيل",
    "resetPassword":"اعادة تعين كلمة المرور",
    "entercode":"ادخل الكود الذي تم ارساله الي :",
    "ShippingExpenses":"مصاريف الشحن",
    "nonotification":"لا يوجد اشعارات لك"
  };
}
