class AR {
  static const Map<String, String> arabic = {
    "lastAdded":"المضاف حديثا",
    "offers":"العروض",
    "bestSeller":"الاكثر مبيعا",
    "category":"الاصناف",
    "wishlist":"المفضلة",
    "subcategory":"الاصناف الفرعية",
    "brand":"براند",
    "orders":"الطلبات",
    "setting":"الاعدادات",
    "Search":"ابحث",
    "langSetting":"اعدادات اللغة",
    "Notifications":"الاشعارات",
    "ShoopingCart":"سلة المشتريات",
    "NoItemsInYourCart":"لا يوجد عناصر في سلة المشتريات لديك",
    "ShppingNow":"تسوق الان",
    "login":"تسجيل الدخول",
    "EnterYourEmail":"ادخل الايميل ",
    "Email":"الايميل",
    "EnterYourPassword":"ادخل كلمة المرور",
    "Password":"كلمة المرور",
    "DontHaveACount":"ليس لديك حساب",
    "SignUp":"اشتراك",
    "ForgetPassword":"هل نسيت كلمة المرور ؟",
    "noReviews":"لا يوجد اي تقيمات لهذا المنتج",
    "Reviews":"التقيمات",
    "phone":"رقم الهاتف",
    "enterPhone":"ادخل رقم الهاتف",
    "enterCountry":"ادخل الدولة",
    "country":"الدولة",
    "City":"المدينة",
    "enterCity":"ادخل المدينة",
    "zone-street":"المنطقة والشارع",
    "enterAddressDetails":"ادخل تفاصيل العنوان",
    "selectAddress":"اختر عنوان التوصيل",
    "confrimDeleteAddress":"تاكيد مسح هذا العنوان",
    "add":"اضافة",
    "cancel":"الغاء",
    "confirm":"تاكيد",
    "addNewAddress":"اضف عنوان جديد",
    "ChooseAddress":"اختر العنوان",
    "Orders":"الطلبات",
    "InProcess":"في التجهيز",
    "OnGoing":"في الطريق",
    "Delivered":"تم التوصيل",
    "Rejected":"تم الرفض",
    "noOrders":"لا يوجد طلبات لديك",
    "NoItemsInFavourite":"لا يوجد عناصر في المفضلة",
    "seeall":"مشاهدة الكل",
    "inprocess":"في التجهيز",
    "ongoing":"في الطريق",
    "delivered":"تم التوصيل",
    "rejected":"تم الرفض",
    "logout":"تسجيل الخروج",
    "lastWatched":"المشاهده مؤخرا",
    "profile":"الملف الشخصي",
    "addresses":"العناوين",
    "currency":"العملة",
    "language":"اللغة",
    "rateapp":"قيم التطبيق",
    "privacyPolices":"سياسة الخصوصية",
    "usagepolices":"سياسة الاستخدام",
    "aboutapp":"عن التطبيق",
    "vendorLogin":"تسجيل الدخول كبائع",
    "addtocart":"اضافة الي السلة",
    "buynow":"شراء الان",
    "store":"المخزن",
    "billdetails":"تفاصيل الفاتورة",
    "totalorders":"اجمالي الطلبات",
    "totalquantity":"اجمالي الكميات",
    "total":"الاجمالي",
    "continuetopurchase":"متابعة الشراء"


  };
}
