class EN {
  static const Map<String, String> english = {
    "lastAdded":"Last Added",
    "offers":"Offers",
    "bestSeller":"Best Seller",
    "category":"Category",
    "wishlist":"Wish List",
    "subcategory":"Sub Category",
    "brand":"Brands",
    "orders":"Orders",
    "setting":"Setting",
    "Search":"Search",
    "langSetting":"langauge Setting",
    "Notifications":"Notifications",
    "ShoopingCart":"Shooping Cart",
    "NoItemsInYourCart":"No Items In Your Cart",
    "ShppingNow":"Shpping Now",
    "login":"Login",
    "EnterYourEmail":"Enter Your Email",
    "Email":"Email",
    "EnterYourPassword":"Enter Your Password",
    "Password":"Password",
    "DontHaveACount":"Dont Have ACount",
    "SignUp":"Sign Up",
    "ForgetPassword":"Forget Password",
    "noReviews":"No Reviews",
    "Reviews":"Reviews",
    "phone":"Phone",
    "enterPhone":"Enter Phone",
    "enterCountry":"Enter Country",
    "country":"Country",
    "City":"City",
    "enterCity":"Enter City",
    "zone-street":"Zone-Street",
    "enterAddressDetails":"Enter Address Details",
    "selectAddress":"Select the delivery address",
    "confrimDeleteAddress":"Confirm Delete This Address",
    "add":"Add",
    "cancel":"Cancel",
    "confirm":"Confirm",
    "addNewAddress":"Add New Address",
    "ChooseAddress":"Choose Address",
    "Orders":"Orders",
    "InProcess":"InProcess",
    "OnGoing":"OnGoing",
    "Delivered":"Delivered",
    "Rejected":"Rejected",
    "noOrders":"No Orders For you",
    "NoItemsInFavourite":"No Items In Favourite"


  };
}
